version: '3.4'

services:
    # Reverse proxy with Traefik
    reverse-proxy:
        image: traefik:v2.3
        container_name: reverse-proxy
        restart: always
        command: --api.insecure=true
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "./docker/reverse-proxy/traefik.yml:/etc/traefik/traefik.yml"
            - "./docker/reverse-proxy/dynamic/:/etc/traefik/traefik.d/"
        networks:
            - proxy
            - monitoring
    
    # Hello World infra
    hello_world:
        build: 
            context: .
            dockerfile: ./docker/hello_world/Dockerfile
        container_name: hello_world
        networks:
            - proxy 
            - redis_bdd
        depends_on:
            - redis

    redis:
        image: redis:6.0-alpine
        container_name: redis
        networks:
            - redis_bdd

    # Monitoring infra 
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        environment:
            - INFLUXDB_DB=${INFLUXDB_DB_NAME}
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=6EQUJ5wow
            - INFLUXDB_USER=${INFLUXDB_USER}
            - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}

        networks:

            - monitoring
    
    grafana:
        image: grafana/grafana
        container_name: grafana
        volumes:
            - "./docker/grafana/grafana.ini:/etc/grafana/grafana.ini"
            - './docker/grafana/provisioning:/etc/grafana/provisioning'
        environment:
            GF_SERVER_DOMAIN: ${ROOT_DOMAIN}
            GF_INSTALL_PLUGINS: "grafana-piechart-panel"
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_AUTH_BASIC_ENABLED: "false"
        networks:
            - proxy
            - monitoring

    # Monitoring infra
    user:
        build:
            context: . 
            dockerfile: ./docker/user_service/Dockerfile
        container_name: user_service
        networks:
            - proxy 
            - mongodb_bdd
        depends_on:
            - mongodb
    
    mongodb:
        image: mongo:latest
        restart: always
        container_name: mongodb
        expose:
            - '3306'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 6EQUJ5wow
            MONGO_INITDB_DATABASE: user_service_db
        networks:
            - mongodb_bdd

networks:
    proxy: # Add this network on your container to expose it on localhost
        name: traefik_network
        driver: bridge
    monitoring: # Add this network on your container to report metrics
        name: monitoring_network
        driver: bridge
    redis_bdd: # Add this network on your container to reach redis node 
        name: redis_network
        driver: bridge
    mongodb_bdd: # Add this network on your container to reach mongodb node 
        name: mongodb_network
