entryPoints:
    web:
        address: ":80"

providers:
    file:
      directory: "/etc/traefik/traefik.d/"
      watch: true

api:
    dashboard: true
    insecure: true


log:
    level: debug

metrics:
    influxDB:
        address: influxdb:8086
        protocol: http
        database: proxy_monitoring
        username: supervisor
        password: very_secret
        addEntryPointsLabels: true
        addServicesLabels: true
        