entryPoints:
    web:
        address: ":80"

providers:
    file:
      directory: "/etc/traefik/traefik.d/"
      watch: true

log:
    level: debug

metrics:
    influxDB:
        address: influxdb:8086
        protocol: http
        database: traefik_monitoring
        username: traefik
        password: traefikpass
        addEntryPointsLabels: true
        addServicesLabels: true
        