http:
    middlewares:
        content_type_autodetect:
            contentType:
                autoDetect: false
                
    routers:
        router-grafana:
            entryPoints:
                - web
            middlewares:
                - content_type_autodetect
            service: grafana
            rule: Host(`monitoring.localhost`)
    
    services:
        grafana:
            loadBalancer:
                servers:
                  - url: "http://grafana:3000/"