http:       
    routers:
        router-hello:
            entryPoints:
                - web
            service: hello_world
            rule: Path(`/`)
    
    services:
        hello_world:
            loadBalancer:
                servers:
                  - url: "http://hello_world:8080/"